// ====== POKÉMON STARTERS DATABASE ======
// Mock data com todos os pokémons iniciais e suas linhas evolutivas
// Formato com sprites Happy, Sad e Dizzy do PMDCollab

const POKEMON_STARTERS = {
  // ====== GERAÇÃO 1 ======
  bulbasaur: { id: 1, name: 'Bulbasaur', types: ['Grass', 'Poison'], primaryColor: '#78C850', generation: 1, height: 0.7, weight: 6.9, evolutionStage: 'base', evolutionLine: ['Bulbasaur', 'Ivysaur', 'Venusaur'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0001/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0001/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0001/Dizzy.png', description: 'Pokémon inicial de tipo Grama/Veneno' },
  ivysaur: { id: 2, name: 'Ivysaur', types: ['Grass', 'Poison'], primaryColor: '#78C850', generation: 1, height: 1.0, weight: 13.0, evolutionStage: 'middle', evolutionLine: ['Bulbasaur', 'Ivysaur', 'Venusaur'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0002/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0002/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0002/Dizzy.png', description: 'Forma evolutiva intermediária de Bulbasaur' },
  venusaur: { id: 3, name: 'Venusaur', types: ['Grass', 'Poison'], primaryColor: '#78C850', generation: 1, height: 2.0, weight: 100.0, evolutionStage: 'final', evolutionLine: ['Bulbasaur', 'Ivysaur', 'Venusaur'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0003/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0003/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0003/Dizzy.png', description: 'Forma final de Bulbasaur' },

  charmander: { id: 4, name: 'Charmander', types: ['Fire'], primaryColor: '#F08030', generation: 1, height: 0.6, weight: 8.5, evolutionStage: 'base', evolutionLine: ['Charmander', 'Charmeleon', 'Charizard'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0004/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0004/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0004/Dizzy.png', description: 'Pokémon inicial de tipo Fogo' },
  charmeleon: { id: 5, name: 'Charmeleon', types: ['Fire'], primaryColor: '#F08030', generation: 1, height: 1.1, weight: 19.0, evolutionStage: 'middle', evolutionLine: ['Charmander', 'Charmeleon', 'Charizard'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0005/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0005/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0005/Dizzy.png', description: 'Forma evolutiva intermediária de Charmander' },
  charizard: { id: 6, name: 'Charizard', types: ['Fire', 'Flying'], primaryColor: '#F08030', generation: 1, height: 1.7, weight: 90.5, evolutionStage: 'final', evolutionLine: ['Charmander', 'Charmeleon', 'Charizard'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0006/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0006/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0006/Dizzy.png', description: 'Forma final de Charmander com tipo Flying' },

  squirtle: { id: 7, name: 'Squirtle', types: ['Water'], primaryColor: '#78C8F0', generation: 1, height: 0.5, weight: 9.0, evolutionStage: 'base', evolutionLine: ['Squirtle', 'Wartortle', 'Blastoise'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0007/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0007/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0007/Dizzy.png', description: 'Pokémon inicial de tipo Água' },
  wartortle: { id: 8, name: 'Wartortle', types: ['Water'], primaryColor: '#78C8F0', generation: 1, height: 1.0, weight: 22.5, evolutionStage: 'middle', evolutionLine: ['Squirtle', 'Wartortle', 'Blastoise'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0008/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0008/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0008/Dizzy.png', description: 'Forma evolutiva intermediária de Squirtle' },
  blastoise: { id: 9, name: 'Blastoise', types: ['Water'], primaryColor: '#78C8F0', generation: 1, height: 1.6, weight: 85.5, evolutionStage: 'final', evolutionLine: ['Squirtle', 'Wartortle', 'Blastoise'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0009/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0009/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0009/Dizzy.png', description: 'Forma final de Squirtle' },

  // ====== GERAÇÃO 2 ======
  chikorita: { id: 152, name: 'Chikorita', types: ['Grass'], primaryColor: '#78C850', generation: 2, height: 0.9, weight: 6.4, evolutionStage: 'base', evolutionLine: ['Chikorita', 'Bayleef', 'Meganium'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0152/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0152/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0152/Dizzy.png', description: 'Pokémon inicial de tipo Grama da Gen 2' },
  bayleef: { id: 153, name: 'Bayleef', types: ['Grass'], primaryColor: '#78C850', generation: 2, height: 1.2, weight: 15.8, evolutionStage: 'middle', evolutionLine: ['Chikorita', 'Bayleef', 'Meganium'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0153/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0153/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0153/Dizzy.png', description: 'Forma evolutiva intermediária de Chikorita' },
  meganium: { id: 154, name: 'Meganium', types: ['Grass'], primaryColor: '#78C850', generation: 2, height: 1.8, weight: 100.5, evolutionStage: 'final', evolutionLine: ['Chikorita', 'Bayleef', 'Meganium'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0154/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0154/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0154/Dizzy.png', description: 'Forma final de Chikorita' },

  cyndaquil: { id: 155, name: 'Cyndaquil', types: ['Fire'], primaryColor: '#F08030', generation: 2, height: 0.5, weight: 7.9, evolutionStage: 'base', evolutionLine: ['Cyndaquil', 'Quilava', 'Typhlosion'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0155/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0155/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0155/Dizzy.png', description: 'Pokémon inicial de tipo Fogo da Gen 2' },
  quilava: { id: 156, name: 'Quilava', types: ['Fire'], primaryColor: '#F08030', generation: 2, height: 0.9, weight: 19.0, evolutionStage: 'middle', evolutionLine: ['Cyndaquil', 'Quilava', 'Typhlosion'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0156/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0156/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0156/Dizzy.png', description: 'Forma evolutiva intermediária de Cyndaquil' },
  typhlosion: { id: 157, name: 'Typhlosion', types: ['Fire'], primaryColor: '#F08030', generation: 2, height: 1.7, weight: 79.5, evolutionStage: 'final', evolutionLine: ['Cyndaquil', 'Quilava', 'Typhlosion'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0157/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0157/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0157/Dizzy.png', description: 'Forma final de Cyndaquil' },

  totodile: { id: 158, name: 'Totodile', types: ['Water'], primaryColor: '#78C8F0', generation: 2, height: 0.6, weight: 9.5, evolutionStage: 'base', evolutionLine: ['Totodile', 'Croconaw', 'Feraligatr'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0158/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0158/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0158/Dizzy.png', description: 'Pokémon inicial de tipo Água da Gen 2' },
  croconaw: { id: 159, name: 'Croconaw', types: ['Water'], primaryColor: '#78C8F0', generation: 2, height: 1.1, weight: 25.0, evolutionStage: 'middle', evolutionLine: ['Totodile', 'Croconaw', 'Feraligatr'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0159/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0159/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0159/Dizzy.png', description: 'Forma evolutiva intermediária de Totodile' },
  feraligatr: { id: 160, name: 'Feraligatr', types: ['Water'], primaryColor: '#78C8F0', generation: 2, height: 2.3, weight: 88.8, evolutionStage: 'final', evolutionLine: ['Totodile', 'Croconaw', 'Feraligatr'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0160/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0160/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0160/Dizzy.png', description: 'Forma final de Totodile' },

  // ====== GERAÇÃO 3 ======
  treecko: { id: 252, name: 'Treecko', types: ['Grass'], primaryColor: '#78C850', generation: 3, height: 0.5, weight: 5.0, evolutionStage: 'base', evolutionLine: ['Treecko', 'Grovyle', 'Sceptile'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0252/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0252/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0252/Dizzy.png', description: 'Pokémon inicial de tipo Grama da Gen 3' },
  grovyle: { id: 253, name: 'Grovyle', types: ['Grass'], primaryColor: '#78C850', generation: 3, height: 0.9, weight: 21.6, evolutionStage: 'middle', evolutionLine: ['Treecko', 'Grovyle', 'Sceptile'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0253/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0253/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0253/Dizzy.png', description: 'Forma evolutiva intermediária de Treecko' },
  sceptile: { id: 254, name: 'Sceptile', types: ['Grass'], primaryColor: '#78C850', generation: 3, height: 1.7, weight: 52.2, evolutionStage: 'final', evolutionLine: ['Treecko', 'Grovyle', 'Sceptile'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0254/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0254/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0254/Dizzy.png', description: 'Forma final de Treecko' },

  torchic: { id: 255, name: 'Torchic', types: ['Fire'], primaryColor: '#F08030', generation: 3, height: 0.4, weight: 2.7, evolutionStage: 'base', evolutionLine: ['Torchic', 'Combusken', 'Blaziken'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0255/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0255/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0255/Dizzy.png', description: 'Pokémon inicial de tipo Fogo da Gen 3' },
  combusken: { id: 256, name: 'Combusken', types: ['Fire', 'Fighting'], primaryColor: '#F08030', generation: 3, height: 0.9, weight: 19.5, evolutionStage: 'middle', evolutionLine: ['Torchic', 'Combusken', 'Blaziken'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0256/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0256/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0256/Dizzy.png', description: 'Forma evolutiva intermediária de Torchic' },
  blaziken: { id: 257, name: 'Blaziken', types: ['Fire', 'Fighting'], primaryColor: '#F08030', generation: 3, height: 1.9, weight: 52.0, evolutionStage: 'final', evolutionLine: ['Torchic', 'Combusken', 'Blaziken'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0257/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0257/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0257/Dizzy.png', description: 'Forma final de Torchic com tipo Fighting' },

  mudkip: { id: 258, name: 'Mudkip', types: ['Water'], primaryColor: '#78C8F0', generation: 3, height: 0.4, weight: 7.6, evolutionStage: 'base', evolutionLine: ['Mudkip', 'Marshtomp', 'Swampert'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0258/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0258/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0258/Dizzy.png', description: 'Pokémon inicial de tipo Água da Gen 3' },
  marshtomp: { id: 259, name: 'Marshtomp', types: ['Water', 'Ground'], primaryColor: '#78C8F0', generation: 3, height: 0.7, weight: 28.0, evolutionStage: 'middle', evolutionLine: ['Mudkip', 'Marshtomp', 'Swampert'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0259/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0259/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0259/Dizzy.png', description: 'Forma evolutiva intermediária de Mudkip' },
  swampert: { id: 260, name: 'Swampert', types: ['Water', 'Ground'], primaryColor: '#78C8F0', generation: 3, height: 1.5, weight: 81.9, evolutionStage: 'final', evolutionLine: ['Mudkip', 'Marshtomp', 'Swampert'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0260/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0260/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0260/Dizzy.png', description: 'Forma final de Mudkip com tipo Ground' },

  // ====== GERAÇÃO 4 ======
  turtwig: { id: 387, name: 'Turtwig', types: ['Grass'], primaryColor: '#78C850', generation: 4, height: 0.4, weight: 10.2, evolutionStage: 'base', evolutionLine: ['Turtwig', 'Grotle', 'Torterra'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0387/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0387/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0387/Dizzy.png', description: 'Pokémon inicial de tipo Grama da Gen 4' },
  grotle: { id: 388, name: 'Grotle', types: ['Grass'], primaryColor: '#78C850', generation: 4, height: 1.1, weight: 64.0, evolutionStage: 'middle', evolutionLine: ['Turtwig', 'Grotle', 'Torterra'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0388/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0388/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0388/Dizzy.png', description: 'Forma evolutiva intermediária de Turtwig' },
  torterra: { id: 389, name: 'Torterra', types: ['Grass', 'Ground'], primaryColor: '#78C850', generation: 4, height: 2.2, weight: 310.0, evolutionStage: 'final', evolutionLine: ['Turtwig', 'Grotle', 'Torterra'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0389/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0389/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0389/Dizzy.png', description: 'Forma final de Turtwig com tipo Ground' },

  chimchar: { id: 390, name: 'Chimchar', types: ['Fire'], primaryColor: '#F08030', generation: 4, height: 0.5, weight: 6.2, evolutionStage: 'base', evolutionLine: ['Chimchar', 'Monferno', 'Infernape'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0390/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0390/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0390/Dizzy.png', description: 'Pokémon inicial de tipo Fogo da Gen 4' },
  monferno: { id: 391, name: 'Monferno', types: ['Fire', 'Fighting'], primaryColor: '#F08030', generation: 4, height: 0.9, weight: 22.0, evolutionStage: 'middle', evolutionLine: ['Chimchar', 'Monferno', 'Infernape'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0391/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0391/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0391/Dizzy.png', description: 'Forma evolutiva intermediária de Chimchar' },
  infernape: { id: 392, name: 'Infernape', types: ['Fire', 'Fighting'], primaryColor: '#F08030', generation: 4, height: 1.2, weight: 55.0, evolutionStage: 'final', evolutionLine: ['Chimchar', 'Monferno', 'Infernape'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0392/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0392/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0392/Dizzy.png', description: 'Forma final de Chimchar com tipo Fighting' },

  piplup: { id: 393, name: 'Piplup', types: ['Water'], primaryColor: '#78C8F0', generation: 4, height: 0.4, weight: 5.2, evolutionStage: 'base', evolutionLine: ['Piplup', 'Prinplup', 'Empoleon'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0393/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0393/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0393/Dizzy.png', description: 'Pokémon inicial de tipo Água da Gen 4' },
  prinplup: { id: 394, name: 'Prinplup', types: ['Water'], primaryColor: '#78C8F0', generation: 4, height: 0.8, weight: 33.5, evolutionStage: 'middle', evolutionLine: ['Piplup', 'Prinplup', 'Empoleon'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0394/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0394/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0394/Dizzy.png', description: 'Forma evolutiva intermediária de Piplup' },
  empoleon: { id: 395, name: 'Empoleon', types: ['Water', 'Steel'], primaryColor: '#78C8F0', generation: 4, height: 1.7, weight: 84.5, evolutionStage: 'final', evolutionLine: ['Piplup', 'Prinplup', 'Empoleon'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0395/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0395/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0395/Dizzy.png', description: 'Forma final de Piplup com tipo Steel' },

  // ====== GERAÇÃO 5 ======
  snivy: { id: 495, name: 'Snivy', types: ['Grass'], primaryColor: '#78C850', generation: 5, height: 0.6, weight: 8.9, evolutionStage: 'base', evolutionLine: ['Snivy', 'Servine', 'Serperior'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0495/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0495/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0495/Dizzy.png', description: 'Pokémon inicial de tipo Grama da Gen 5' },
  servine: { id: 496, name: 'Servine', types: ['Grass'], primaryColor: '#78C850', generation: 5, height: 0.8, weight: 17.3, evolutionStage: 'middle', evolutionLine: ['Snivy', 'Servine', 'Serperior'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0496/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0496/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0496/Dizzy.png', description: 'Forma evolutiva intermediária de Snivy' },
  serperior: { id: 497, name: 'Serperior', types: ['Grass'], primaryColor: '#78C850', generation: 5, height: 3.0, weight: 63.0, evolutionStage: 'final', evolutionLine: ['Snivy', 'Servine', 'Serperior'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0497/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0497/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0497/Dizzy.png', description: 'Forma final de Snivy' },

  tepig: { id: 498, name: 'Tepig', types: ['Fire'], primaryColor: '#F08030', generation: 5, height: 0.5, weight: 9.9, evolutionStage: 'base', evolutionLine: ['Tepig', 'Pignite', 'Emboar'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0498/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0498/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0498/Dizzy.png', description: 'Pokémon inicial de tipo Fogo da Gen 5' },
  pignite: { id: 499, name: 'Pignite', types: ['Fire', 'Fighting'], primaryColor: '#F08030', generation: 5, height: 1.0, weight: 55.5, evolutionStage: 'middle', evolutionLine: ['Tepig', 'Pignite', 'Emboar'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0499/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0499/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0499/Dizzy.png', description: 'Forma evolutiva intermediária de Tepig' },
  emboar: { id: 500, name: 'Emboar', types: ['Fire', 'Fighting'], primaryColor: '#F08030', generation: 5, height: 1.6, weight: 150.0, evolutionStage: 'final', evolutionLine: ['Tepig', 'Pignite', 'Emboar'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0500/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0500/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0500/Dizzy.png', description: 'Forma final de Tepig com tipo Fighting' },

  oshawott: { id: 501, name: 'Oshawott', types: ['Water'], primaryColor: '#78C8F0', generation: 5, height: 0.5, weight: 5.9, evolutionStage: 'base', evolutionLine: ['Oshawott', 'Dewott', 'Samurott'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0501/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0501/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0501/Dizzy.png', description: 'Pokémon inicial de tipo Água da Gen 5' },
  dewott: { id: 502, name: 'Dewott', types: ['Water'], primaryColor: '#78C8F0', generation: 5, height: 0.8, weight: 24.2, evolutionStage: 'middle', evolutionLine: ['Oshawott', 'Dewott', 'Samurott'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0502/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0502/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0502/Dizzy.png', description: 'Forma evolutiva intermediária de Oshawott' },
  samurott: { id: 503, name: 'Samurott', types: ['Water'], primaryColor: '#78C8F0', generation: 5, height: 1.5, weight: 94.6, evolutionStage: 'final', evolutionLine: ['Oshawott', 'Dewott', 'Samurott'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0503/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0503/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0503/Dizzy.png', description: 'Forma final de Oshawott' },

  // ====== GERAÇÃO 6 ======
  chespin: { id: 650, name: 'Chespin', types: ['Grass'], primaryColor: '#78C850', generation: 6, height: 0.4, weight: 4.0, evolutionStage: 'base', evolutionLine: ['Chespin', 'Quilladin', 'Chesnaught'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0650/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0650/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0650/Dizzy.png', description: 'Pokémon inicial de tipo Grama da Gen 6' },
  quilladin: { id: 651, name: 'Quilladin', types: ['Grass'], primaryColor: '#78C850', generation: 6, height: 0.7, weight: 14.8, evolutionStage: 'middle', evolutionLine: ['Chespin', 'Quilladin', 'Chesnaught'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0651/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0651/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0651/Dizzy.png', description: 'Forma evolutiva intermediária de Chespin' },
  chesnaught: { id: 652, name: 'Chesnaught', types: ['Grass', 'Fighting'], primaryColor: '#78C850', generation: 6, height: 1.6, weight: 90.0, evolutionStage: 'final', evolutionLine: ['Chespin', 'Quilladin', 'Chesnaught'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0652/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0652/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0652/Dizzy.png', description: 'Forma final de Chespin com tipo Fighting' },

  fennekin: { id: 653, name: 'Fennekin', types: ['Fire'], primaryColor: '#F08030', generation: 6, height: 0.4, weight: 9.4, evolutionStage: 'base', evolutionLine: ['Fennekin', 'Braixen', 'Delphox'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0653/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0653/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0653/Dizzy.png', description: 'Pokémon inicial de tipo Fogo da Gen 6' },
  braixen: { id: 654, name: 'Braixen', types: ['Fire'], primaryColor: '#F08030', generation: 6, height: 1.0, weight: 14.5, evolutionStage: 'middle', evolutionLine: ['Fennekin', 'Braixen', 'Delphox'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0654/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0654/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0654/Dizzy.png', description: 'Forma evolutiva intermediária de Fennekin' },
  delphox: { id: 655, name: 'Delphox', types: ['Fire', 'Psychic'], primaryColor: '#F08030', generation: 6, height: 1.5, weight: 39.0, evolutionStage: 'final', evolutionLine: ['Fennekin', 'Braixen', 'Delphox'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0655/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0655/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0655/Dizzy.png', description: 'Forma final de Fennekin com tipo Psychic' },

  froakie: { id: 656, name: 'Froakie', types: ['Water'], primaryColor: '#78C8F0', generation: 6, height: 0.3, weight: 7.2, evolutionStage: 'base', evolutionLine: ['Froakie', 'Frogadier', 'Greninja'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0656/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0656/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0656/Dizzy.png', description: 'Pokémon inicial de tipo Água da Gen 6' },
  frogadier: { id: 657, name: 'Frogadier', types: ['Water'], primaryColor: '#78C8F0', generation: 6, height: 0.6, weight: 10.9, evolutionStage: 'middle', evolutionLine: ['Froakie', 'Frogadier', 'Greninja'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0657/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0657/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0657/Dizzy.png', description: 'Forma evolutiva intermediária de Froakie' },
  greninja: { id: 658, name: 'Greninja', types: ['Water', 'Dark'], primaryColor: '#78C8F0', generation: 6, height: 1.5, weight: 40.0, evolutionStage: 'final', evolutionLine: ['Froakie', 'Frogadier', 'Greninja'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0658/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0658/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0658/Dizzy.png', description: 'Forma final de Froakie com tipo Dark' },

  // ====== GERAÇÃO 7 ======
  rowlet: { id: 722, name: 'Rowlet', types: ['Grass', 'Flying'], primaryColor: '#78C850', generation: 7, height: 0.3, weight: 1.5, evolutionStage: 'base', evolutionLine: ['Rowlet', 'Dartrix', 'Decidueye'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0722/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0722/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0722/Dizzy.png', description: 'Pokémon inicial de tipo Grama/Flying da Gen 7' },
  dartrix: { id: 723, name: 'Dartrix', types: ['Grass', 'Flying'], primaryColor: '#78C850', generation: 7, height: 0.7, weight: 16.0, evolutionStage: 'middle', evolutionLine: ['Rowlet', 'Dartrix', 'Decidueye'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0723/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0723/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0723/Dizzy.png', description: 'Forma evolutiva intermediária de Rowlet' },
  decidueye: { id: 724, name: 'Decidueye', types: ['Grass', 'Ghost'], primaryColor: '#78C850', generation: 7, height: 1.6, weight: 34.0, evolutionStage: 'final', evolutionLine: ['Rowlet', 'Dartrix', 'Decidueye'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0724/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0724/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0724/Dizzy.png', description: 'Forma final de Rowlet com tipo Ghost' },

  litten: { id: 725, name: 'Litten', types: ['Fire'], primaryColor: '#F08030', generation: 7, height: 0.4, weight: 4.3, evolutionStage: 'base', evolutionLine: ['Litten', 'Torracat', 'Incineroar'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0725/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0725/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0725/Dizzy.png', description: 'Pokémon inicial de tipo Fogo da Gen 7' },
  torracat: { id: 726, name: 'Torracat', types: ['Fire'], primaryColor: '#F08030', generation: 7, height: 0.9, weight: 25.0, evolutionStage: 'middle', evolutionLine: ['Litten', 'Torracat', 'Incineroar'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0726/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0726/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0726/Dizzy.png', description: 'Forma evolutiva intermediária de Litten' },
  incineroar: { id: 727, name: 'Incineroar', types: ['Fire', 'Dark'], primaryColor: '#F08030', generation: 7, height: 1.8, weight: 83.0, evolutionStage: 'final', evolutionLine: ['Litten', 'Torracat', 'Incineroar'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0727/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0727/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0727/Dizzy.png', description: 'Forma final de Litten com tipo Dark' },

  popplio: { id: 728, name: 'Popplio', types: ['Water'], primaryColor: '#78C8F0', generation: 7, height: 0.4, weight: 7.5, evolutionStage: 'base', evolutionLine: ['Popplio', 'Brionne', 'Primarina'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0728/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0728/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0728/Dizzy.png', description: 'Pokémon inicial de tipo Água da Gen 7' },
  brionne: { id: 729, name: 'Brionne', types: ['Water'], primaryColor: '#78C8F0', generation: 7, height: 0.6, weight: 17.5, evolutionStage: 'middle', evolutionLine: ['Popplio', 'Brionne', 'Primarina'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0729/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0729/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0729/Dizzy.png', description: 'Forma evolutiva intermediária de Popplio' },
  primarina: { id: 730, name: 'Primarina', types: ['Water', 'Fairy'], primaryColor: '#78C8F0', generation: 7, height: 1.8, weight: 44.0, evolutionStage: 'final', evolutionLine: ['Popplio', 'Brionne', 'Primarina'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0730/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0730/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0730/Dizzy.png', description: 'Forma final de Popplio com tipo Fairy' },

  // ====== GERAÇÃO 8 ======
  grookey: { id: 810, name: 'Grookey', types: ['Grass'], primaryColor: '#78C850', generation: 8, height: 0.3, weight: 2.6, evolutionStage: 'base', evolutionLine: ['Grookey', 'Thwackey', 'Rillaboom'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0810/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0810/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0810/Dizzy.png', description: 'Pokémon inicial de tipo Grama da Gen 8' },
  thwackey: { id: 811, name: 'Thwackey', types: ['Grass'], primaryColor: '#78C850', generation: 8, height: 0.7, weight: 16.0, evolutionStage: 'middle', evolutionLine: ['Grookey', 'Thwackey', 'Rillaboom'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0811/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0811/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0811/Dizzy.png', description: 'Forma evolutiva intermediária de Grookey' },
  rillaboom: { id: 812, name: 'Rillaboom', types: ['Grass'], primaryColor: '#78C850', generation: 8, height: 2.1, weight: 90.0, evolutionStage: 'final', evolutionLine: ['Grookey', 'Thwackey', 'Rillaboom'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0812/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0812/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0812/Dizzy.png', description: 'Forma final de Grookey' },

  scorbunny: { id: 813, name: 'Scorbunny', types: ['Fire'], primaryColor: '#F08030', generation: 8, height: 0.3, weight: 4.5, evolutionStage: 'base', evolutionLine: ['Scorbunny', 'Raboot', 'Cinderace'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0813/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0813/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0813/Dizzy.png', description: 'Pokémon inicial de tipo Fogo da Gen 8' },
  raboot: { id: 814, name: 'Raboot', types: ['Fire'], primaryColor: '#F08030', generation: 8, height: 0.6, weight: 9.0, evolutionStage: 'middle', evolutionLine: ['Scorbunny', 'Raboot', 'Cinderace'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0814/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0814/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0814/Dizzy.png', description: 'Forma evolutiva intermediária de Scorbunny' },
  cinderace: { id: 815, name: 'Cinderace', types: ['Fire'], primaryColor: '#F08030', generation: 8, height: 1.4, weight: 33.0, evolutionStage: 'final', evolutionLine: ['Scorbunny', 'Raboot', 'Cinderace'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0815/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0815/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0815/Dizzy.png', description: 'Forma final de Scorbunny' },

  sobble: { id: 816, name: 'Sobble', types: ['Water'], primaryColor: '#78C8F0', generation: 8, height: 0.3, weight: 3.6, evolutionStage: 'base', evolutionLine: ['Sobble', 'Drizzile', 'Inteleon'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0816/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0816/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0816/Dizzy.png', description: 'Pokémon inicial de tipo Água da Gen 8' },
  drizzile: { id: 817, name: 'Drizzile', types: ['Water'], primaryColor: '#78C8F0', generation: 8, height: 0.7, weight: 11.3, evolutionStage: 'middle', evolutionLine: ['Sobble', 'Drizzile', 'Inteleon'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0817/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0817/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0817/Dizzy.png', description: 'Forma evolutiva intermediária de Sobble' },
  inteleon: { id: 818, name: 'Inteleon', types: ['Water'], primaryColor: '#78C8F0', generation: 8, height: 1.6, weight: 25.2, evolutionStage: 'final', evolutionLine: ['Sobble', 'Drizzile', 'Inteleon'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0818/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0818/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0818/Dizzy.png', description: 'Forma final de Sobble' },

  // ====== GERAÇÃO 9 ======
  sprigatito: { id: 906, name: 'Sprigatito', types: ['Grass'], primaryColor: '#78C850', generation: 9, height: 0.4, weight: 2.4, evolutionStage: 'base', evolutionLine: ['Sprigatito', 'Floragato', 'Meowscarada'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0906/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0906/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0906/Dizzy.png', description: 'Pokémon inicial de tipo Grama da Gen 9' },
  floragato: { id: 907, name: 'Floragato', types: ['Grass'], primaryColor: '#78C850', generation: 9, height: 0.9, weight: 9.3, evolutionStage: 'middle', evolutionLine: ['Sprigatito', 'Floragato', 'Meowscarada'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0907/Normal.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0907/Normal.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0907/Dizzy.png', description: 'Forma evolutiva intermediária de Sprigatito' },
  meowscarada: { id: 908, name: 'Meowscarada', types: ['Grass', 'Dark'], primaryColor: '#78C850', generation: 9, height: 1.5, weight: 25.0, evolutionStage: 'final', evolutionLine: ['Sprigatito', 'Floragato', 'Meowscarada'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0908/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0908/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0908/Dizzy.png', description: 'Forma final de Sprigatito com tipo Dark' },

  fuecoco: { id: 909, name: 'Fuecoco', types: ['Fire'], primaryColor: '#F08030', generation: 9, height: 0.4, weight: 9.8, evolutionStage: 'base', evolutionLine: ['Fuecoco', 'Crocalor', 'Skeledirge'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0909/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0909/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0909/Dizzy.png', description: 'Pokémon inicial de tipo Fogo da Gen 9' },
  crocalor: { id: 910, name: 'Crocalor', types: ['Fire'], primaryColor: '#F08030', generation: 9, height: 1.0, weight: 25.0, evolutionStage: 'middle', evolutionLine: ['Fuecoco', 'Crocalor', 'Skeledirge'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0910/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0910/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0907/Normal%5E.png', description: 'Forma evolutiva intermediária de Fuecoco' },
  skeledirge: { id: 911, name: 'Skeledirge', types: ['Fire', 'Ghost'], primaryColor: '#F08030', generation: 9, height: 2.0, weight: 110.0, evolutionStage: 'final', evolutionLine: ['Fuecoco', 'Crocalor', 'Skeledirge'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0911/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0911/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0911/Dizzy.png', description: 'Forma final de Fuecoco com tipo Ghost' },

  quaxly: { id: 912, name: 'Quaxly', types: ['Water'], primaryColor: '#78C8F0', generation: 9, height: 0.5, weight: 5.0, evolutionStage: 'base', evolutionLine: ['Quaxly', 'Quaxwell', 'Quaquaval'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0912/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0912/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0912/Dizzy.png', description: 'Pokémon inicial de tipo Água da Gen 9' },
  quaxwell: { id: 913, name: 'Quaxwell', types: ['Water'], primaryColor: '#78C8F0', generation: 9, height: 1.0, weight: 16.0, evolutionStage: 'middle', evolutionLine: ['Quaxly', 'Quaxwell', 'Quaquaval'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0913/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0913/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0913/Dizzy.png', description: 'Forma evolutiva intermediária de Quaxly' },
  quaquaval: { id: 914, name: 'Quaquaval', types: ['Water', 'Fighting'], primaryColor: '#78C8F0', generation: 9, height: 1.8, weight: 61.0, evolutionStage: 'final', evolutionLine: ['Quaxly', 'Quaxwell', 'Quaquaval'], sprite: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0914/Happy.png', spriteSad: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0914/Sad.png', spriteDizzy: 'https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0914/Dizzy.png', description: 'Forma final de Quaxly com tipo Fighting' }
};

function getAllStarters() { return Object.values(POKEMON_STARTERS); }
function getAllPokemon() { return Object.values(POKEMON_STARTERS); } // Por enquanto retorna os mesmos starters
function getStarterByName(name) { const key = name.toLowerCase(); return POKEMON_STARTERS[key] || null; }
function getStartersByGeneration(gen) { return Object.values(POKEMON_STARTERS).filter(pokemon => pokemon.generation === gen); }
function getStartersByType(type) { return Object.values(POKEMON_STARTERS).filter(pokemon => pokemon.types.includes(type)); }
function getEvolutionLines() {
  const lines = [];
  const seen = new Set();
  Object.values(POKEMON_STARTERS).forEach(pokemon => {
    const lineKey = pokemon.evolutionLine.join('|');
    if (!seen.has(lineKey)) {
      seen.add(lineKey);
      lines.push({ line: pokemon.evolutionLine, type: pokemon.types[0], generation: pokemon.generation });
    }
  });
  return lines;
}
